
version: '3.1'

services:
    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile.dev
        command: npm run start
        ports:
            - "3000:3000"
        stdin_open: true
        volumes:
            - ./frontend/src:/frontend/src

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
              - '80:80'
        depends_on:
            - frontend

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
